# Generated by Django 3.2.12 on 2022-04-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220409_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Departament',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeNome',
            new_name='EmployeeName',
        ),
    ]
