# Generated by Django 3.2.12 on 2022-04-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220409_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
